In [1]:
#importing the dataset
import pandas as pd
import math
%matplotlib inline

data = pd.read_csv('data.csv')

#showing first five rows of data (before transformation)
data.head(5)

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,...,department_finishing,department_finishing,department_sweing,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday,actual_productivity
0,9,0.75,3.94,NaN,960,0,0.0,0,0,8.0,...,1,0,0,0,0,0,0,0,1,0.755167
1,7,0.65,30.10,909.0,7080,0,0.0,0,1,59.0,...,0,0,1,0,0,0,1,0,0,0.535678
2,3,0.80,4.15,NaN,1440,0,0.0,0,0,7.0,...,0,1,0,0,0,0,0,0,1,0.820833
3,1,0.65,22.53,762.0,5040,0,0.0,0,1,42.0,...,0,0,1,0,0,0,0,0,1,0.581131
4,4,0.70,30.10,767.0,3300,50,0.0,0,1,57.0,...,0,0,1,1,0,0,0,0,0,0.790003

In [2]:
#data transformations

def day_column():
    day = []
    for index, row in data.iterrows():
        if(row['day_Monday'] == 1):
            day.append("Monday")
        elif (row['day_Tuesday'] == 1):
            day.append("Tuesday")
        elif (row['day_Wednesday'] == 1):
            day.append("Wednesday")
        elif (row['day_Thursday'] == 1):
            day.append("Thursday")
        elif (row['day_Saturday'] == 1):
            day.append("Saturday")
        elif (row['day_Sunday'] == 1):
            day.append("Sunday")
    remove_cols = ['day_Monday', 'day_Tuesday', 'day_Wednesday', 'day_Thursday', 'day_Saturday', 'day_Sunday']
    data.drop(columns=remove_cols, inplace=True)
    data["day"] = day
data.head(5)

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,...,department_finishing,department_finishing,department_sweing,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday,actual_productivity
0,9,0.75,3.94,NaN,960,0,0.0,0,0,8.0,...,1,0,0,0,0,0,0,0,1,0.755167
1,7,0.65,30.10,909.0,7080,0,0.0,0,1,59.0,...,0,0,1,0,0,0,1,0,0,0.535678
2,3,0.80,4.15,NaN,1440,0,0.0,0,0,7.0,...,0,1,0,0,0,0,0,0,1,0.820833
3,1,0.65,22.53,762.0,5040,0,0.0,0,1,42.0,...,0,0,1,0,0,0,0,0,1,0.581131
4,4,0.70,30.10,767.0,3300,50,0.0,0,1,57.0,...,0,0,1,1,0,0,0,0,0,0.790003

In [3]:
def quarter_column():
    quarter = []
    for index, row in data.iterrows():
        if(row['quarter_Quarter1'] == 1):
            quarter.append(1)
        elif(row['quarter_Quarter2'] == 1):
            quarter.append(2)
        elif(row['quarter_Quarter3'] == 1):
            quarter.append(3)
        elif(row['quarter_Quarter4'] == 1):
            quarter.append(4)
        elif(row['quarter_Quarter5'] == 1):
            quarter.append(5)
    
    col_remove = ['quarter_Quarter1', 'quarter_Quarter2', 'quarter_Quarter3', 'quarter_Quarter4', 'quarter_Quarter5']
    data.drop(columns=col_remove, inplace=True)
    data['quarter_num'] = quarter
data.head(5)

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,...,department_finishing,department_finishing,department_sweing,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday,actual_productivity
0,9,0.75,3.94,NaN,960,0,0.0,0,0,8.0,...,1,0,0,0,0,0,0,0,1,0.755167
1,7,0.65,30.10,909.0,7080,0,0.0,0,1,59.0,...,0,0,1,0,0,0,1,0,0,0.535678
2,3,0.80,4.15,NaN,1440,0,0.0,0,0,7.0,...,0,1,0,0,0,0,0,0,1,0.820833
3,1,0.65,22.53,762.0,5040,0,0.0,0,1,42.0,...,0,0,1,0,0,0,0,0,1,0.581131
4,4,0.70,30.10,767.0,3300,50,0.0,0,1,57.0,...,0,0,1,1,0,0,0,0,0,0.790003

In [4]:
def department_column():
    department = []
    for index,row in data.iterrows():
        if (row['department_sweing'] == 1):
            department.append('sweing')
        else:
            department.append('finishing')
    
    col_remove = ['department_sweing', 'department_finishing', 'department_finishing']
    data.drop(columns=col_remove, inplace=True)
    data['department'] = department
data.head(5)

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,...,department_finishing,department_finishing,department_sweing,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday,actual_productivity
0,9,0.75,3.94,NaN,960,0,0.0,0,0,8.0,...,1,0,0,0,0,0,0,0,1,0.755167
1,7,0.65,30.10,909.0,7080,0,0.0,0,1,59.0,...,0,0,1,0,0,0,1,0,0,0.535678
2,3,0.80,4.15,NaN,1440,0,0.0,0,0,7.0,...,0,1,0,0,0,0,0,0,1,0.820833
3,1,0.65,22.53,762.0,5040,0,0.0,0,1,42.0,...,0,0,1,0,0,0,0,0,1,0.581131
4,4,0.70,30.10,767.0,3300,50,0.0,0,1,57.0,...,0,0,1,1,0,0,0,0,0,0.790003

In [5]:
def add_idle_column():
    idle_time = []
    idle_men = []
    for item,row in data.iterrows():
        if(row['idle_men'] != 0):
            idle_men.append(True)
        else:
            idle_men.append(False)
        if(row['idle_time'] != 0.0):
            idle_time.append(True)
        else:
            idle_time.append(False)
    data['idle_time?'] = idle_time
    data['idle_men?'] = idle_men
data.head(5)

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,...,department_finishing,department_finishing,department_sweing,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday,actual_productivity
0,9,0.75,3.94,NaN,960,0,0.0,0,0,8.0,...,1,0,0,0,0,0,0,0,1,0.755167
1,7,0.65,30.10,909.0,7080,0,0.0,0,1,59.0,...,0,0,1,0,0,0,1,0,0,0.535678
2,3,0.80,4.15,NaN,1440,0,0.0,0,0,7.0,...,0,1,0,0,0,0,0,0,1,0.820833
3,1,0.65,22.53,762.0,5040,0,0.0,0,1,42.0,...,0,0,1,0,0,0,0,0,1,0.581131
4,4,0.70,30.10,767.0,3300,50,0.0,0,1,57.0,...,0,0,1,1,0,0,0,0,0,0.790003

In [ ]:
def num_workers_column():
    data['no_of_workers'] = data['no_of_workers'].apply(lambda x: math.ceil(x))

def wip_column():
    data['wip'] = data['wip'].fillna(0)

def remove_month_column():
    data.drop(columns='month', inplace=True)
data.head(5)

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,...,department_finishing,department_finishing,department_sweing,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday,actual_productivity
0,9,0.75,3.94,NaN,960,0,0.0,0,0,8.0,...,1,0,0,0,0,0,0,0,1,0.755167
1,7,0.65,30.10,909.0,7080,0,0.0,0,1,59.0,...,0,0,1,0,0,0,1,0,0,0.535678
2,3,0.80,4.15,NaN,1440,0,0.0,0,0,7.0,...,0,1,0,0,0,0,0,0,1,0.820833
3,1,0.65,22.53,762.0,5040,0,0.0,0,1,42.0,...,0,0,1,0,0,0,0,0,1,0.581131
4,4,0.70,30.10,767.0,3300,50,0.0,0,1,57.0,...,0,0,1,1,0,0,0,0,0,0.790003

In [7]:
#make the transformations and read into new csv

day_column()   
quarter_column()
department_column()  
add_idle_column()  
num_workers_column()
wip_column()
remove_month_column()
data.head(5)

new_csv_file = 'transformed_data.csv'

# Save the transformed data to a new CSV file
data.to_csv(new_csv_file, index=False)